### PR TITLE
Include forceEviction option in destroy

### LINKED ISSUE #28: Calling `.destroy()` throws exception
When a user calls `.destroy()` at the moment it automatically performs a `ctx.abort(..)` eviction of the instance but that causes the application to immediately throw an exception.

Option 1 is to make it an `opts` to perform this operation.

Test:
- An Actor calling `.destroy()` on itself
- Another instance calling `.destroy()` on another Actor

Expected:
- App should continue to perform as expected without throwing exception, unless evicting the current Actor.

### PR DESCRIPTION
**Pull request by Brayden**
Instead of always running the `this.ctx.abort("destroyed");` code when calling `Actor.destroy()` we are wrapping it in an option named `forceEviction` that is false by default.

When you do decide to opt in to the `forceEviction` we would recommend wrapping this logic in a try/catch block. The reason behind this is because when we do an RPC call into a Durable Object instance, this particular code execution to `abort` will throw an exception which in turn returns that response to the caller (in the below example would be the `MyDeleteInstanceEntrypoint`). Without it wrapped in a try/catch the implementing class will also throw that exception and your code execution will end.

```typescript
export class MyDeleteInstanceEntrypoint extends Entrypoint<Env> {
    async fetch(request: Request): Promise<Response> {
        // Deleting a specific instance inside our tracking instance
        const actor = MyStorageActor.get('foobar');
        
        // Wrap in a try/catch because the `forceEviction` flag of an Actor instance
        // will throw an exception which is propogated back through the RPC mechanism
        // of our worker.
        try {
            await actor.destroy({ forceEviction: true });
        } catch (e) { }

        return new Response('Actor deleted');
    }
}
export default handler(MyDeleteInstanceWorker);
```

Resolves #28

### CODE REVIEW

File: packages/core/src/index.ts [hunk 1]
```diff
@@ -146,8 +146,12 @@ export abstract class Actor<E> extends DurableObject<E> {
     /**
      * Destroy the Actor by removing all actor library specific tables and state
      * that is associated with the actor.
+     * @param _ - Optional configuration object
+     * @param _.trackingInstance - Optional tracking instance name
+     * @param _.forceEviction - When true, forces eviction of the actor from the cache
+     * @throws Will throw an exception when forceEviction is true
      */
-    async destroy(_?: { trackingInstance?: string }) {
+    async destroy(_?: { trackingInstance?: string, forceEviction?: boolean }) {
```
Comment (Brayden) [inline packages/core/src/index.ts:154]: Remove `trackingInstance`
